// flow-typed signature: 819e9a2393ffa77f6fa722633cd9317a
// flow-typed version: <<STUB>>/doggie_model_v^1.0.0/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'doggie_model'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'doggie_model' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'doggie_model/src/FundModel' {
  declare module.exports: any;
}

declare module 'doggie_model/src/FundModel.test' {
  declare module.exports: any;
}

declare module 'doggie_model/src/utils/Utils' {
  declare module.exports: any;
}

declare module 'doggie_model/src/utils/Utils.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'doggie_model/index' {
  declare module.exports: $Exports<'doggie_model'>;
}
declare module 'doggie_model/index.js' {
  declare module.exports: $Exports<'doggie_model'>;
}
declare module 'doggie_model/src/FundModel.js' {
  declare module.exports: $Exports<'doggie_model/src/FundModel'>;
}
declare module 'doggie_model/src/FundModel.test.js' {
  declare module.exports: $Exports<'doggie_model/src/FundModel.test'>;
}
declare module 'doggie_model/src/utils/Utils.js' {
  declare module.exports: $Exports<'doggie_model/src/utils/Utils'>;
}
declare module 'doggie_model/src/utils/Utils.test.js' {
  declare module.exports: $Exports<'doggie_model/src/utils/Utils.test'>;
}
